export const NATIONALITIES = [
  "Afghane", "Sud-africaine", "Albanaise", "Algérienne", "Allemande", "Andorrane", "Angolaise", "Antiguaise", "Saoudienne", "Argentine", "Arménienne", "Australienne", "Autrichienne", "Azerbaïdjanaise",
  "Bahaméenne", "Bahreïnie", "Bangladaise", "Barbadienne", "Biélorusse", "Belge", "Bélizienne", "Béninoise", "Bhoutanaise", "Birmane", "Bolivienne", "Bosnienne", "Botswanaise", "Brésilienne", "Brunéienne", "Bulgare", "Burkinabé", "Burundaise",
  "Cambodgienne", "Camerounaise", "Canadienne", "Cap-verdienne", "Centrafricaine", "Chilienne", "Chinoise", "Chypriote", "Colombienne", "Comorienne", "Congolaise", "Nord-coréenne", "Sud-coréenne", "Costaricienne", "Ivoirienne", "Croate", "Cubaine",
  "Danoise", "Djiboutienne", "Dominicaine",
  "Égyptienne", "Émirienne", "Équatorienne", "Érythréenne", "Espagnole", "Estonienne", "Eswatinienne", "Américaine", "Éthiopienne",
  "Fidjienne", "Finlandaise", "Française",
  "Gabonaise", "Gambienne", "Géorgienne", "Ghanéenne", "Grecque", "Grenadienne", "Guatémaltèque", "Guinéenne", "Bissau-guinéenne", "Équato-guinéenne", "Guyanienne",
  "Haïtienne", "Hondurienne", "Hongroise",
  "Marshallaise", "Salomonaise", "Indienne", "Indonésienne", "Irakienne", "Iranienne", "Irlandaise", "Islandaise", "Israélienne", "Italienne",
  "Jamaïcaine", "Japonaise", "Jordanienne",
  "Kazakhe", "Kényane", "Kirghize", "Kiribatienne", "Koweïtienne",
  "Laotienne", "Lesothane", "Lettone", "Libanaise", "Libérienne", "Libyenne", "Liechtensteinoise", "Lituanienne", "Luxembourgeoise",
  "Nord-macédonienne", "Malgache", "Malaisienne", "Malawienne", "Maldivienne", "Malienne", "Maltaise", "Marocaine", "Mauricienne", "Mauritanienne", "Mexicaine", "Micronésienne", "Moldave", "Monégasque", "Mongole", "Monténégrine", "Mozambicaine",
  "Namibienne", "Nauruane", "Népalaise", "Nicaraguayenne", "Nigérienne", "Nigériane", "Norvégienne", "Néo-zélandaise",
  "Omanaise", "Ougandaise", "Ouzbèke",
  "Pakistanaise", "Palaosienne", "Palestinienne", "Panaméenne", "Papouane", "Paraguayenne", "Néerlandaise", "Péruvienne", "Philippine", "Polonaise", "Portugaise",
  "Qatarienne",
  "Roumaine", "Britannique", "Russe", "Rwandaise",
  "Kittitienne", "Lucienne", "Saint-marinaise", "Vincentaise", "Salvadorienne", "Samoane", "Santoméenne", "Sénégalaise", "Serbe", "Seychelloise", "Sierra-léonaise", "Singapourienne", "Slovaque", "Slovène", "Somalienne", "Soudanaise", "Sud-soudanaise", "Sri-lankaise", "Suédoise", "Suisse", "Surinamaise", "Syrienne",
  "Tadjike", "Tanzanienne", "Tchadienne", "Tchèque", "Thaïlandaise", "Timoraise", "Togolaise", "Tongienne", "Trinidadienne", "Tunisienne", "Turkmène", "Turque", "Tuvaluane",
  "Ukrainienne", "Uruguayenne",
  "Vanuatuane", "Vaticane", "Vénézuélienne", "Vietnamienne",
  "Yéménite",
  "Zambienne", "Zimbabwéenne"
];