// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otifwbmkdjjfhlueddrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90aWZ3Ym1rZGpqZmhsdWVkZHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjczMTcsImV4cCI6MjA3Mjc0MzMxN30.4TgncPatbqzSqmWEIPEofrvrOWSVApaOOOd0pENdDWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});